import json
import re
import subprocess
import sys
from pathlib import Path


ROOT_PATH = Path(__file__).parents[0]
CONFIG_PATH = ROOT_PATH / "src" / "cfg" / "config.json"
AFFIRMATIVE_ANSWERS = {"y", "yes"}
SCRIPT_BRANCH_PATTERN = re.compile(
    r"^(feat|fix|chore|refactor|docs|style|perf)/[a-z]+-\d{4}$"
)


def main():
    repository = load_repository()
    open_prs = list_open_prs(repository)

    if not open_prs:
        print("No open PRs found.")
        return

    generated_prs = [pr for pr in open_prs if is_generated_pr(pr)]
    other_prs = [pr for pr in open_prs if not is_generated_pr(pr)]

    print(f"Repository: {repository}")
    print(f"Open PRs total:    {len(open_prs)}")
    print(f"  Generated by script: {len(generated_prs)}")
    print(f"  Other PRs:           {len(other_prs)}")

    target_prs = pick_targets(generated_prs, other_prs)
    if not target_prs:
        print("Nothing to close. Exiting.")
        return

    preview_targets(target_prs)

    confirmation = input(
        f"Close {len(target_prs)} PR(s) and delete branches? (y/N): "
    ).strip().lower()
    if confirmation not in AFFIRMATIVE_ANSWERS:
        print("Cancelled.")
        return

    closed_count, failed_count = close_targets(repository, target_prs)
    print(f"--- Closed: {closed_count}, Failed: {failed_count} ---")


def load_repository():
    if not CONFIG_PATH.exists():
        print(f"Config not found at {CONFIG_PATH}. Run main.py first.")
        sys.exit(1)

    with open(CONFIG_PATH, "r", encoding="utf-8") as file:
        config = json.load(file)

    repository = config.get("repository", "").strip()
    if not repository:
        print("Repository field is empty in config.json.")
        sys.exit(1)

    return repository


def list_open_prs(repository):
    result = run_gh(
        [
            "pr",
            "list",
            "--repo",
            repository,
            "--state",
            "open",
            "--limit",
            "1000",
            "--json",
            "number,title,headRefName",
        ]
    )
    return json.loads(result)


def is_generated_pr(pr):
    return bool(SCRIPT_BRANCH_PATTERN.match(pr["headRefName"]))


def pick_targets(generated_prs, other_prs):
    if not other_prs:
        return generated_prs

    print()
    print("Some open PRs do not match the script branch pattern.")
    print("Choose scope:")
    print("  1) Generated PRs only (safe)")
    print("  2) All open PRs (DANGEROUS, includes manual PRs)")
    print("  3) Cancel")
    selection = input("Selection [1]: ").strip() or "1"

    if selection == "1":
        return generated_prs
    if selection == "2":
        return generated_prs + other_prs
    return []


def preview_targets(target_prs, sample_size=10):
    print()
    print("Sample of PRs to close:")
    for pr in target_prs[:sample_size]:
        print(f"  #{pr['number']:>5}  {pr['headRefName']:<40}  {pr['title']}")
    remaining = len(target_prs) - sample_size
    if remaining > 0:
        print(f"  ... and {remaining} more")
    print()


def close_targets(repository, target_prs):
    closed_count = 0
    failed_count = 0

    for pr in target_prs:
        try:
            run_gh(
                [
                    "pr",
                    "close",
                    str(pr["number"]),
                    "--repo",
                    repository,
                    "--delete-branch",
                ]
            )
            print(f"Closed #{pr['number']} {pr['headRefName']}")
            closed_count += 1
        except CloseError as error:
            failed_count += 1
            print(f"Failed #{pr['number']}: {error}")

    return closed_count, failed_count


class CloseError(Exception):
    pass


def run_gh(arguments):
    try:
        result = subprocess.run(
            ["gh", *arguments],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as error:
        raise CloseError("gh CLI is not available on PATH") from error
    except subprocess.CalledProcessError as error:
        message = (error.stderr or error.stdout or "").strip()
        raise CloseError(message or "gh command failed") from error
    return result.stdout


if __name__ == "__main__":
    try:
        main()
    except CloseError as error:
        print(f"Error: {error}")
        sys.exit(1)
